services:
  matatika:
    image: matatika/catalog:${VER_MATATIKA}
    restart: unless-stopped
    container_name: ${PKG_NAME}-matatika
    user: root
    deploy:
      resources:
        reservations:
          memory: 1g
        limits:
          memory: 3g
    environment:
      - SERVER_PORT=80
      - SERVER_SSL_ENABLED=false
      - REACT_APP_ENV=distribution
      - SPRING_H2_CONSOLE_ENABLED=false
      - ACTIVE_PROFILES=default,distribution
      - "JAVA_OPTS=-XX:MaxDirectMemorySize=1G -XX:MaxMetaspaceSize=240234K -XX:ReservedCodeCacheSize=240M -Xss1M -Xms512m -Xmx1040584K"
      - MATATIKA_WORKSPACES_HOME=/workspaces
      - MATATIKA_PLUGINS_HOME=/plugins,/plugins-staging,file:/local-plugins
    env_file:
      - path: ${RUN}/.env
        required: true
      - path: ${LOT}/.env
        required: true
      - path: ${LOT}/sup/config/.env
        required: true
    networks:
      - default
    volumes:
      - workspaces:/workspaces
      - plugins:/local-plugins
    healthcheck:
      test: curl -fs http://localhost/actuator/health | grep '^\{"status":"UP"' > /dev/null
      interval: 10s
      timeout: 10s
      start_period: 120s
      retries: 5

networks:
  default:
    external: true
    name: ${PKG_NAME}

volumes:
  workspaces:
    name: ${PKG_NAME}-matatika-workspaces
  plugins:
    name: ${PKG_NAME}-matatika-plugins