global:
  database:
    type: internal
    host: postgres
    port: 5432
    database: airbyte
    user: airbyte
    password: __password__

postgresql:
  enabled: false

temporal:
  enabled: true
  extraEnv:
    - name: DBNAME
      value: "airbyte_temporal"
    - name: VISIBILITY_DBNAME
      value: "airbyte_temporal_visibility"
    - name: SKIP_DB_CREATE
      value: "true"
