#!/bin/bash

git=$(which git)
dkr=$(which docker)
dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -a
. $dir/.env
set +a

rm -rf $dir/dist/*

chmod 755 $dir/docker/cmd/*/*.sh
chmod 755 $dir/docker/src/services/*/*.sh

$dkr --debug build --no-cache --build-arg PKG_NAME=$PKG_NAME --tag jfforg/$PKG_NAME:${1:-$PKG_VTAG} .

for out in "purge" "setup"; do
	cat $dir/$out | envsubst '$PKG_NAME $PKG_VTAG' > $dir/dist/$out
done