services:
  baserow:
    image: baserow/baserow:${VER_BASEROW}
    restart: unless-stopped
    container_name: ${PKG_NAME}-baserow
    env_file:
      - path: ${RUN}/.env
        required: true
      - path: ${LOT}/.env
        required: true
    networks:
      - default
    volumes:
      - data:/baserow/data

networks:
  default:
    external: true
    name: ${PKG_NAME}

volumes:
  data:
    name: ${PKG_NAME}-baserow-data