#!/bin/bash
declare -Ax OPTS
declare -ax ARGS

APP="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

. $APP/.env

VOL="/$PKG_NAME"
RUN="$VOL/run"

if [ ! -d "$RUN" ]; then
    mkdir $RUN
    touch $RUN/.env
fi

. $RUN/.env

goto() {
    local dir="$(pwd)/$1"

    if [ ! -d "$dir" ]; then
        echo "Invalid command or subcommand '$1' in '$ARGS'"
        exit 1
    fi

    echo $dir
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -*)
            name="${1##*-}"

            eval "$name="1""

            if [[ "$2" != "" ]]; then
                case $2 in
                    -*) ;;
                    *)
                        eval "$name=\"$2\""
                        shift 2
                    ;;
                esac
            fi

            shift 1
        ;;
        *)
            ARGS+=("$1")
            shift 1
        ;;
  esac
done

set -- "${ARGS[@]}"

cd $APP/cmd

dkr=$(which docker)

for sub in $ARGS; do
    cd $(goto $sub)
done

if [[ $help == "1" ]]; then
    cat help.adoc
    exit 0
fi

. run.sh
