#!/bin/bash
declare -Ax OPTS
declare -ax ARGS

cd "$( dirname "${BASH_SOURCE[0]}" )"

ENV="$(pwd)/../data/.env"

touch $ENV
. $ENV
. ../.env


goto() {
    local dir="$(pwd)/$1"

    if [ ! -d "$dir" ]; then
        echo "Invalid command or subcommand '$1' in '$ARGS'"
        exit 1
    fi

    cd $dir
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -*)
            name="${1##*-}"

            eval "$name="1""

            if [[ "$2" != "" ]]; then
                case $2 in
                    -*) ;;
                    *)
                        eval "$name=\"$2\""
                        shift 2
                    ;;
                esac
            fi

            shift 1
        ;;
        *)
            ARGS+=("$1")
            shift 1
        ;;
  esac
done

set -- "${ARGS[@]}"

goto "cmd"

dkr=$(which docker)

for sub in $ARGS; do
    goto $sub
done

if [[ $help == "1" ]]; then
    cat help.adoc
    exit 0
fi

. run.sh
